name: Semantic Release

on:
#   push:
#     branches:
#       - main
    workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write  # Required for PyPI trusted publishing

jobs:
  # test:
  #   uses: ./.github/workflows/test.yml

  release:
    name: Release
    # needs: test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mcp-science
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # - name: Generate token
      #   id: generate_token
      #   uses: tibdex/github-app-token@v2
      #   with:
      #     app_id: ${{ secrets.BOT_APP_ID }}
      #     private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v4
      #   with:
      #     version: 8
      #     run_install: false

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 'lts/*'
      #     cache: 'pnpm'

      # - name: Install dependencies
      #   run: pnpm install

      # - name: Semantic Release
      #   id: semantic
      #   uses: cycjimmy/semantic-release-action@v4
      #   env:
      #     GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Install uv with caching
        # if: steps.semantic.outputs.new_release_published == 'true'
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Build
        # if: steps.semantic.outputs.new_release_published == 'true'
        run: uv build

      - name: Publish distribution to PyPI
        # if: steps.semantic.outputs.new_release_published == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1 